services:
  mysql:
    image: mysql:latest
    container_name: ah_metroevents_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bmetroevents
      MYSQL_USER: admin_root
      MYSQL_PASSWORD: admin_root
    ports:
      - 3310:3306
    networks:
      - ag
    volumes:
      - mysql_data:/var/lib/mysql

  
  backend:
    image: python:3.9-slim  # Usa una imagen ligera de Python
    working_dir: /app
    volumes:
      - ./backend-fastapi:/app  # Monta tu directorio local de código
    ports:
      - "8020:8000"  # Expone el puerto 8020 para FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    # Instalar dependencias antes de ejecutar uvicorn
    entrypoint: >
      sh -c "
      pip install --no-cache-dir uvicorn fastapi &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - ag

  apache:
    image: httpd:latest
    ports:
      - 7010:7010
    volumes:
      - ./app:/usr/local/apache2/htdocs/

  redis:
    image: redis:latest
    ports:
      - 7087:6379
    volumes:
      - redis_data:/data

  adminer:
    image: adminer:latest
    ports:
      - 7630:8080

volumes:
  mysql_data:
  redis_data:

networks:
  ag:
    external: true
