-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 09:56:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema metroevents
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bmetroevents
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bmetroevents` ;

-- -----------------------------------------------------
-- Schema bmetroevents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bmetroevents` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `bmetroevents` ;

-- -----------------------------------------------------
-- Table `bmetroevents`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bmetroevents`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `event_category` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `organizer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `organizer_id_idx` (`organizer_id` ASC) VISIBLE,
  CONSTRAINT `organizer_id`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `bmetroevents`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `bmetroevents`.`events`
ADD COLUMN `attendees` INT DEFAULT 0;

-- -----------------------------------------------------
-- Table `bmetroevents`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`comments` (
  `comments_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `event_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(100) NOT NULL,
  `rating` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`comments_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `bmetroevents`.`events` (`event_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmetroevents`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bmetroevents`.`event_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`event_categories` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bmetroevents`.`event_category_assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`event_category_assignments` (
  `event_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `eventc_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `event`
    FOREIGN KEY (`event_id`)
    REFERENCES `bmetroevents`.`events` (`event_id`),
  CONSTRAINT `eventc`
    FOREIGN KEY (`category_id`)
    REFERENCES `bmetroevents`.`event_categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bmetroevents`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`notifications` (
  `notifications_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `event_id` INT NULL DEFAULT NULL,
  `message` VARCHAR(200) NOT NULL,
  `sent_at` DATE NOT NULL,
  PRIMARY KEY (`notifications_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `evento`
    FOREIGN KEY (`event_id`)
    REFERENCES `bmetroevents`.`events` (`event_id`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmetroevents`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bmetroevents`.`user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmetroevents`.`user_profiles` (
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `biografia` VARCHAR(100) NULL DEFAULT NULL,
  `update_at` VARCHAR(45) NOT NULL,
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmetroevents`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
